name: gym_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  animated_bottom_navigation_bar: ^1.1.0+1
  path_provider: ^2.0.12
  persistent_bottom_nav_bar: ^5.0.2
  http: ^0.13.5
  webview_flutter: ^4.0.5
  youtube_player_flutter: ^8.1.2
  duration: ^3.0.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
